### PR TITLE
Decode multiple rows more efficiently

### PR DESCRIPTION
**Pull request by fishcakez**
Decode row values while decoding the packet and reduce binary references per row.

@scohen please try your old benchmark on this, we may get near parity with java...

### CODE REVIEW

**Comment by fishcakez** [comment]
Ah theres a conflict, I have rebased. @liveforeverx to confirm this change means mariaex is slightly faster than a java client for a large number of rows.

**Comment by scohen** [comment]
Confirmed; we're at parity with the java drivers now.

**Comment by josevalim** [comment]
@liveforeverx any chance we can get this one and #157 merged into a new release? I am working on the last RC for Ecto 2.1 and I want to make sure those bugs are fixed and tested before final. :heart:

**Comment by liveforeverx** [comment]
@josevalim sorry for delay, off course, yes.

**Comment by liveforeverx** [comment]
@fishcakez Thank you!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
